"""Constant values for the game of Gnom"""

FONT_NAME = 'freesansbold.ttf'
FONT_SIZE = 32
TEXT_COLOR = (240, 200, 250)

GOLD_AMOUNT = 10
CELL_SIZE = 20
CELL_AMOUNT_Y = 13
CELL_AMOUNT_X = 30

GRID_LINE_COLOR = (50, 50, 50)
GRID_LINE_WIDTH = 2

GOLD_COLOR = (255, 215, 0)
GOLD_RADIUS = 8

EXIT_COLOR = (240, 200, 160)
EXIT_Y = CELL_AMOUNT_Y // 2
EXIT_X = CELL_AMOUNT_X - 1

GNOM_Y = 0
GNOM_X = 0
GNOM_RADIUS = 10
GNOM_COLOR = (200, 50, 100)
GNOM_VISION_COLOR = (50, 200, 50)
GNOM_VISION_SIZE = 2

USED_COORDS = [
    {
        "x": GNOM_X,
        "y": GNOM_Y
    },
    {
        "x": EXIT_X,
        "y": EXIT_Y
    }
]

FPS = 30
MARGIN = 60
SPEED = [1, 2, 3, 5, 6, 10, 15, 30]
MODE = ["player", "ai"]
GAME_BACKGROUND = (0, 0, 0)
MARGIN_BACKGROUND = (150, 0, 0)
SCOREBOARD_HEIGHT = 100
SCOREBOARD_BACKGROUND = (50, 50, 50)
SCOREBOARD_SEPARATOR_WIDTH = 2
SCOREBOARD_SEPARATOR_COLOR = (150, 150, 150)
POSSIBLE_ACTIONS = {
    "gnom": [0, 1, 2, 3]
}

"""COMMON TUNABLE VARIABLES"""
GAME_SPEED = 1
GAME_MODE = "player"

SCREEN_WIDTH = CELL_SIZE * CELL_AMOUNT_X + MARGIN * 2
SCREEN_HEIGHT = CELL_SIZE * CELL_AMOUNT_Y + MARGIN * 2 + SCOREBOARD_HEIGHT
GAME_PLAY_HEIGHT = CELL_SIZE * CELL_AMOUNT_Y
GAME_PLAY_WIDTH = CELL_SIZE * CELL_AMOUNT_X
